project:
  type: website
  output-dir: docs

website:
  title: "Transport Data Science"
  repo-url: https://github.com/itsleeds/tds
  repo-actions: [edit]
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/itsleeds/tds
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      # - href: module-info.qmd
      #   text: Module Information
      - href: https://itsleeds.github.io/tds/#software-requirements-and-installation
        text: Install required software
      - href: schedule.qmd
        text: Schedule
      - href: https://github.com/ITSLeeds/TDS/discussions
        text: Forum
      - href: marking-criteria.qmd
        text: Marking Criteria
      - href: reading.qmd
        text: Reading list
      - href: minihack-transport-data.qmd
        text: Transport Data Minihack 8th May
      - href: dstp.qmd
        text: Data Science for Transport Planning 2 day course
      # - href: precourse-interactive.qmd
      #   text: Pre-Course Self-Assessment (Interactive)
      - href: precourse.qmd
        text: Pre-Course Self-Assessment
      - href: reproducible-road-safety-workshop.qmd
        text: Reproducible Road Safety Workshop
      - text: Sessions
        contents:
          - href: d1
            text: Introduction and setup
          - href: s1
            text: Session 1
          - href: s2
            text: Session 2
          - href: s3
            text: "Session 3: AI for Transport Planning"
          - href: s4
            text: Session 4
          - href: s5
            text: Session 5
          - href: sem1
            text: Seminar 1
          - href: d2
            text: Formative assessment
          - href: sem2
            text: Seminar 2
          - href: s6
            text: "Session 6: Joins, models and publishing"
          - href: d3
            text: Coursework submission

      #       href: p5
      #       text: Practical 5
      #     - href: p6
      #       text: Practical 6
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
    # content: "**Alert** ensure you have completed the second homework, described at the end of [itsleeds.github.io/tds/s1](https://itsleeds.github.io/tds/s1/#homework) by this Thursday 6th February."
    # content: "**Homework to present at the next session**: Ensure you have completed the second homework, described at the end of [itsleeds.github.io/tds/s3](https://itsleeds.github.io/tds/s3/#homework) by **Thursday 20th February**. Note: there will be a session (10:00-13:00) AND a seminar (14:00-17:00) on this day. Location: Institute for Transport Studies, room 1.11."
    # content: "**Deadline for the [formative assessment](https://itsleeds.github.io/tds/d2) is Friday 28th February.**"
    # type: primary
    # position: below-navbar

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true
    number-sections: true
    csl: elsevier-harvard.csl

execute:
  freeze: auto
  cache: true
  daemon: false
